apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: "/etc/config"
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap
        items:
          - key: key1
            path: config-key1
          - key: key2
            path: config-key2
